CREATE TABLE notifications (
  id SERIAL NOT NULL PRIMARY KEY,
  read BOOLEAN NOT NULL DEFAULT false,
  message VARCHAR(300) NOT NULL,
  from_uid UUID NOT NULL,
  to_uid UUID NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY ("from_uid") REFERENCES "users"(user_uid),
  FOREIGN KEY ("to_uid") REFERENCES "users"(user_uid)
);