CREATE TABLE posts (
  id SERIAL NOT NULL PRIMARY KEY,
  post_uid UUID NOT NULL UNIQUE DEFAULT uuid_generate_v4(),
  title VARCHAR(200) NOT NULL,
  body TEXT,
  slug VARCHAR(150) NOT NULL,
  identifier VARCHAR(150) NOT NULL,
  sub_name VARCHAR(150) NOT NULL,
  user_uid UUID REFERENCES users(user_uid),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP 
)